### user list

GET http://localhost:8001/user/list

### product list
GET http://localhost:8003/product/list


### order list
GET http://localhost:8002/order/list



### order create
POST http://localhost:8002/order
Content-Type: application/json
Accept: application/json

{
  "userId": 1,
  "products": [
    { "productId": 1, "quantity": 2 }
  ]
}
